version: "3.8"
services:
  web:
    build: ./app
    image: 999429981407.dkr.ecr.us-east-2.amazonaws.com/django_docker_aws:trailer_to_lane
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
    - DB_NAME=trailertolanedb
    - DB_USER=postgres
    - DB_PASSWORD=admin123
    - DB_HOST=trailertolanedb.cxzksgujoald.us-east-2.rds.amazonaws.com
    - DB_PORT=5432
    - DATABASE=postgres
  pgadmin:
      container_name: pgadmin_containr
      image: dpage/pgadmin4:5.2
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@example.com
          PGADMIN_DEFAULT_PASSWORD: admin123
          PGADMIN_LISTEN_PORT: 5433
          PGADMIN_CONFIG_SERVER_MODE: "False"
          PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      ports:
          - "5433:5433"
      depends_on:
          - web