# Generated by Django 3.2.2 on 2023-02-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_lane', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trailer')),
            ],
        ),
    ]
